memgraph/orb

src/models/graph.ts, src/models/node.ts
It fixes the following issue:
```typescript
orb.data.setDefaultStyle({
getNodeStyle(node) {
return {
imageUrl: "https://image.com/image.png",
};
},
});
orb.data.setup({ nodes, edges });
orb.view.render();
const node = orb.data.getNodesById(0);
node.style.imageUrl = "https://image.com/new-image.png"
```
Orb knows about default style and it will check each default style when applied to new nodes. This means it will check for values in `imageUrl` and `imageUrlSelected` in order to get those images in the browser cache. The problem is that the line where `node.style.imageUrl` is set, Orb doesn't know about it, so the image is never loaded in the browser cache, not it will be rendered.
So a `Graph` that is connected to the `ImageHandler` service that fetches images is now using the node's …
=> Fix: Fix image loading on node style properties

.idea/modules.xml, src/models/strategy.ts, src/views/default-view.ts, src/views/map-view.ts
Issue: When hovering over nodes/edges, the `OrbEventType.MOUSE_MOVE` event will have a defined subject (node or edge) only on the first event, but it should be present in all `MOUSE_MOVE` events while the mouse pointer is on top of the node or edge.
* `OrbEventType.MOUSE_MOVE` will be emitted for each mouse move event. If the mouse pointer is on top of the node or edge, `event.subject` will be a node or an edge object. If the mouse pointer is not on top of node or edge, `event.subject` will be `undefined`.
* `OrbEventType.NODE_HOVER` will be triggered only once for each subject: a node or an edge. It is like a "mouse pointer entered node space".
=> Fix: Fix undefined subject on mouse hover event

src/utils/html.utils.spec.ts, src/utils/html.utils.ts, src/views/default-view.ts, src/views/map-view.ts
* Set dimensions on parent element when undefined (https://github.com/memgraph/orb/issues/23)
* Preserve graph container children (https://github.com/memgraph/orb/issues/22)
=> Chore: Set dimensions on parent element, Preserve graph container contents

docs/view-default.md, docs/view-map.md, src/renderer/canvas/canvas-renderer.ts, src/renderer/factory.ts, src/renderer/shared.ts, src/renderer/webgl/webgl-renderer.ts, src/utils/function.utils.ts, src/utils/math.utils.ts, src/views/default-view.ts, src/views/map-view.ts, test/utils/html.utils.spec.ts
Fixes issue: #15 
A throttle is added for `render` calls to skip renders depending on the defined FPS (frame per second) parameter. This will enable users to call `orb.view.render()` within events without fear to have performance issues.
New settings parameter is available, `render.fps`, with a default value of `60`. It can be changed anytime.
=> Fix: Add throttle render to renderer via fps settings

src/views/default-view.ts
It fixes the following issue:
If you use Orb like this:
* Render the graph after which you want to `console.log` a message and recenter the graph
* After 5 seconds, change the view settings by enabling physics
```
orb.view.render(() => {
console.log('Rendering done');
orb.view.recenter();
});
setTimeout(() => {
orb.view.setSettings({
render: {
isPhysicsEnabled: true,
},
});
}, 5000)
```
The problem:
* When enabling the physics, simulation of the nodes will start
* When the simulation ends, it will call the same callback from the first render (`console.log` and recenter)
The solution:
* After calling the user's callback, remove it so it is not called anymore in simulation end event
=> Fix: Remove render callback after first usage in simulation end

src/views/map-view.ts
Having multiple map views with default map tiles didn't work since they all reused the same tile. Added a factory function to create multiple instances.
=> Fix: Fix multiple maps issue

src/simulator/types/web-worker-simulator/simulator.ts
This fixed the issue #28 for me with Parcel. I believe the `module` is needed to instruct the bundler that it's an esmodule and should be bundled.
https://stackoverflow.com/questions/48045569/whats-the-difference-between-a-classic-and-module-web-worker
=> Fix web worker build with parcel

docs/events.md, examples/example-graph-events.html, src/events.ts, src/models/strategy.ts, src/views/default-view.ts, src/views/map-view.ts, webpack.config.js
This PR will add support for context menu events (mouse right click), the library exposes the 3 new events 
```
1. NODE_RIGHT_CLICK  :  Triggered when a node on the canvas is clicked
2. EDGE_RIGHT_CLICK : Triggered when an edge is clicked.
3. CANVAS_RIGHT_CLICK : Triggered when the canvas is clicked.
``` 
For example, to handle NODE_RIGHT_CLICK event we can use
```
orb.events.on(Orb.OrbEventType.NODE_RIGHT_CLICK, (data) => {
data.event.preventDefault();
console.log("Node Right Clicked", data);
})
```
=> New: Added support for context menu events

docs/events.md, examples/example-graph-events.html, src/events.ts, src/models/strategy.ts, src/views/default-view.ts, src/views/map-view.ts
This PR will add support for double click events, the library exposes the 3 new events 
```
1. NODE_DOUBLE_CLICK :  Triggered when a node on the canvas is double clicked
2. EDGE_DOUBLE_CLICK : Triggered when an edge is double clicked.
3. MOUSE_DOUBLE_CLICK: Triggered when the canvas is double clicked.
``` 
For example, to handle NODE_DOUBLE_CLICK event we can use
```
orb.events.on(Orb.OrbEventType.NODE_DOUBLE_CLICK , (data) => {
console.log("Node Double Clicked", data);
})
```
=> New: Added support for double click events

docs/view-default.md, docs/view-map.md, examples/example-custom-styled-graph.html, src/renderer/canvas/canvas-renderer.ts, src/renderer/shared.ts
The following PR adds additional property (`render.backgroundColor`) that can be set via view settings. It supports hex colors and `Color` objects, including transparent colors (RGBA, HSLA, ...).
To change the background color, call the following code:
```typescript
orb.view.setSettings({
render: {
backgroundColor: '#DDDDDD',
},
});
// reset the background color with
orb.view.setSettings({
render: {
backgroundColor: null,
},
});
```
It works for both the default view and the map view. Map view is interesting when using colors with alpha (transparency channel):
=> New: Add canvas background color

docs/styles.md, examples/example-custom-styled-graph.html, src/models/edge.ts, src/models/graph.ts, src/models/node.ts, src/renderer/canvas/canvas-renderer.ts, src/utils/entity.utils.ts, test/utils/entity.utils.spec.ts
Additional `zIndex` property on nodes and edges that act similar to CSS z-index. If set on any of the nodes, the zIndex property value will be used as a stack order when rendering nodes/edges.
An example "Custom styled graph" has been updated where the first node has the highest zIndex value.
=> New: Add zIndex style property

src/models/graph.ts
Issue: #60 
**Description:**
This pull request addresses the issue raised regarding the lack of a straightforward way to retrieve selected/hovered nodes and edges in the library. To enhance the flexibility and functionality of the library, this PR introduces four new methods, `getSelectedNodes`, `getSelectedEdges`, `getHoveredNodes`, `getHoveredEdges`. Which enable users to retrieve all selected/hovered elements within the graph.
**Changes Made:**
- Implemented the `getSelectedNodes` method to retrieve all selected nodes.
- Implemented the `getSelectedEdges` method to retrieve all selected edges.
- Implemented the `getHoveredNodes` method to retrieve all hovered nodes.
- Implemented the `getHoveredEdges` method to retrieve all hovered edges.
**Example Usage:**
```typescript
// Retrieve …
```
=> New: Added support to get selected/hovered nodes and edges

src/models/graph.ts
Adds missing sort functionality for the edges in regards to `zIndex` property.
=> Fix: Add the correct sort for the edge zIndex

docs/view-default.md, src/views/orb-view.ts
**Description:**
This pull request introduces enhancements related to zooming functionality. The changes aim to provide users with more control over zooming interactions. Here's an overview of the modifications made:
- Added a new property `isZoomEnabled` to the optional interaction object.
- `isZoomEnabled` allows users to enable or disable the zooming feature in the graph.
- When `isZoomEnabled` is set to `true`, users can interactively zoom in and out of the graph.
- When `isZoomEnabled` is set to `false`, zooming functionality is disabled, restricting users from changing the zoom level.
**Example:**
```typescript
//To enable zooming
orb.setSettings({ interaction: { isZoomEnabled: true } });
```
```typescript
//To disable zooming
orb.setSettings({ interaction: { isZoomEnabled: false } …
```
=> New: Add support for enabling and disabling zoom (fixes #62)

docs/view-default.md, docs/view-map.md, src/renderer/canvas/canvas-renderer.ts, src/renderer/factory.ts, src/renderer/shared.ts, src/renderer/webgl/webgl-renderer.ts, src/utils/html.utils.ts, src/views/orb-map-view.ts, src/views/orb-view.ts
The following PR adds support for automatic and manual handling of `devicePixelRatio`. More information about `devicePixelRatio` can be found here: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
There are two modes: Automatic and Manual.
*Automatic `devicePixelRatio` handler (default)*
The default behavior is the automatic handler of the `devicePixelRatio` value and changes (e.g. user drags a view from one display to another with a different DPR value). The automatic handler is turned on when the settings value `render.devicePixelRatio` equals to `null`.
*Manual `devicePixelRatio` handler*
If you want to manually handle the `devicePixelRatio` values, just set the settings value `render.devicePixelRatio` to a numeric DPR value. Orb will stop listening for DPR …
=> New: Add support for handling device pixel ratio

src/models/graph.ts, src/utils/array.utils.ts
This PR introduces functions for removing all data, nodes (the same functionality as removing all the data), or edges by reusing existing remove function. It can be used as follows:
```typescript
orb.data.removeAll();
orb.data.removeAllNodes();
orb.data.removeAllEdges();
```
=> New: Add removal functions

src/simulator/engine/d3-simulator-engine.ts
Resolves #89
This PR slightly changes the default simulator engine settings to place them in a better layout location. It can be seen in `localhost:8080/example-graph-data-changes.html` and in the simulator example 3.4.1. However, it does not fix it for bigger graphs where layout change could be helpful.
=> Fix: Default settings for node placement

src/models/edge.ts, src/models/graph.ts, src/models/node.ts, src/models/state.ts, src/utils/observer.utils.ts
Resolves #68
As an enhancement to the freshly implemented getters and setters, this PR introduces a new way to set the state of nodes and edges using objects that specify state with additional parameters such as `isSingle` and `isToggle`. Now, it is possible to use both the regular setter:
```typescript
node.setState(state)
```
and the new setter:
```typescript
node.setState({ state: GraphObjectState.SELECTED, options: { isSingle: true } })
```
```typescript
edge.setState({ state: GraphObjectState.SELECTED, options: { isSingle: false, isToggle: true } })
```
and so on. This provides more customization flexibility to the user, with default values for these parameters set to `false`. It should be easily extendable for adding even more options.
=> New: Add state setters with options

src/views/orb-view.ts
This PR introduces `zoomIn` and `zoomOut` functions for the new `orb-view` API. They can be used as follows:
```typescript
const orb = new Orb.OrbView(container, ...);
orb.zoomIn();
orb.zoomOut();
```
=> New: Add zoom in and out functions

tsconfig.json
This PR disables unnecessary source map generation while building.
Fixes #99
=> Fix: Disable source map generation
